version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: satapp
      POSTGRES_PASSWORD: satapp123
      POSTGRES_DB: sat_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
