// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type AnswerChoice struct {
	ID         int32
	QuestionID sql.NullInt32
	ChoiceText string
	IsCorrect  sql.NullBool
	CreatedAt  sql.NullTime
}

type Question struct {
	ID              int32
	SubjectID       sql.NullInt32
	QuestionText    string
	CorrectAnswer   string
	DifficultyLevel sql.NullInt32
	Explanation     sql.NullString
	CreatedAt       sql.NullTime
}

type Subject struct {
	ID        int32
	Name      string
	CreatedAt sql.NullTime
}
